theme: jekyll-theme-merlot
exclude: [ backups ]
title: 富乎·地问
description: >
  <br><img src="assets/images/avatar.png" alt="avatar" width="64" height="64" style="border:none" />
  <br>辗转探寻为富乎？《天问》无解向地问！
  <br><br><a href="https://foofoodamon.github.io/" target="_top" style="color: white">&lt;&lt;&lt; 返回主页</a>
